apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app2
spec:
  rules:
  - host: demo2.local
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 3000